### PR TITLE
MOVING COUNTRY CODE TABLE INITIALIZATION TO COMPLY WITH ARM5 COMPILER

### PR DESCRIPTION
**Pull request by JeanMarcR**
MOVING COUNTRY CODE TABLE INITIALIZATION TO COMPLY WITH ARM5 COMPILER

### CODE REVIEW

**Comment by jeromecoutant** [comment]
@mtomczykmobica
@LMESTM

**Comment by jeromecoutant** [comment]
@MarceloSalazar @LMESTM 
Should we merge this kind of correction as ARM5 is not supported in MBED6 ?
Solution could be to provide a mbed5 branch without #73 ?

**Comment by LMESTM** [comment]
What is the compilation error or warning ?
I'd also be surprised that this is the only possible fix ...

**Comment by jeromecoutant** [comment]
Hi

> Should we merge this kind of correction as ARM5 is not supported in MBED6 ?
> Solution could be to provide a mbed5 branch without #73 ?

mbed-os-5.15 branch has been created before #73 
So this PR is no more needed as context is now mbed-os-6 only

**Pull request closed without merging**
