### PR TITLE
Fix console debug 

### PR DESCRIPTION
**Pull request by evedon**
Enable debug traces if MBED_CONF_MBED_TRACE_ENABLE and MBED_CONF_ISM43362_WIFI_DEBUG are set.

### CODE REVIEW

**Review by jeromecoutant — CHANGES_REQUESTED** [review]
I am afraid that "or"was intentional...

**Comment by teetak01** [comment]
Could we consider as alternative that we drop the `ism_interface_debug `flag, and just control the tracing via the `debug`?

So changing the tracing of this driver would not have any dependency on mbed-trace configuration?

We have noticed some trace-breaking issues on our side in certain scenarios. Mbed trace supports mutex-locking, but if some component does run-time printf's, it can break trace-lines and cause testing failures.

**Comment by evedon** [comment]
In my application, I have mbed traces enabled and I do not want to see ism43362 traces.
@teetak01 's suggestion would work for me.

**Comment by jeromecoutant** [comment]
Changing (and keep ism_interface_debug || debug):
````
// activate / de-activate debug
#if MBED_CONF_MBED_TRACE_ENABLE
#define ism_interface_debug 1
#else
#define ism_interface_debug 0
#endif
````
By
````
// Set 1 to force debug information
#define ism_interface_debug 0
````
Would be OK for you ?

**Comment by jeromecoutant** [comment]
@evedon see above proposition
Thx

**Comment by evedon** [comment]
Yes, that's perfect!

**Review by jeromecoutant — APPROVED** [review]

**Pull request merged**
