### PR TITLE
Improving robustness[WIP]

### PR DESCRIPTION
**Pull request by JeanMarcR**
- adding mutex lock/unlock

### CODE REVIEW

**Review by LMESTM — APPROVED** [review]
LGTM !

**Comment by jeromecoutant** [comment]
Got some error. Not 100% systematic

Ex with B_L4S5I_IOT01A and DNS test:
```
[1613749469.36][CONN][RXD] >>> Running case #9: 'ASYNCHRONOUS_DNS_TIMEOUTS'...
[1613749469.40][CONN][INF] found KV pair in stream: {{__testcase_start;ASYNCHRONOUS_DNS_TIMEOUTS}}, queued...
[1613749473.09][CONN][RXD]
[1613749473.09][CONN][RXD]
[1613749473.11][CONN][RXD] ++ MbedOS Error Info ++
[1613749473.15][CONN][RXD] Error Status: 0x80010137 Code: 311 Module: 1
[1613749473.21][CONN][RXD] Error Message: EventFlags: 0x20002F6C, Parameter error
[1613749473.23][CONN][RXD] Location: 0x8016F31
[1613749473.27][CONN][RXD] Error Value: 0x20002F6C
[1613749473.39][CONN][RXD] Current Thread: application_unnamed_thread Id: 0x2000300C Entry: 0x800D23D StackSize: 0x800 StackMem: 0x20007270 SP: 0x2009FF4C

```

**Comment by JeanMarcR** [comment]
@jeromecoutant 
I performed  ASYNCHRONOUS_DNS_TIMEOUTS 10 times without any errors ...
I do not know how to reproduce the problem ...
@teetak01
Please, could you check if the problem is still present ?

**Comment by teetak01** [comment]
We have been running some internal tests on this and looks to be working quite well. At least I have not seen any regression due to this.

**Review by teetak01 — APPROVED** [review]

**Comment by JeanMarcR** [comment]
@teetak01 
Did you success in registration the board in PELION ?
(https://portal.mbedcloud.com/devices/list)

**Comment by LMESTM** [comment]
@JeanMarcR  thx for the good work on improving the driver. 
I'd prefer to see 2 separate commits : 1 for the lock / unlock improvements which is quite easy to review and understand, and another commit, with more explanation and details, about padding management. The Inventek firmware sepc clearly mentions 0x15 padding, but nothing about 0x3E, so I'm not sure to understand

**Comment by LMESTM** [comment]
@JeanMarcR, you said:
> The last useful character is ">" -> ASCII (0x3E).
So, I check the presence of ">" and I flush.
But after the ">" there are useless characters (0x15) which were previously removed
Please, is it possible to continue this conversation in PR (#90) which is up to date now.

OK, that explains the code you have added.
But also I can read in the spec that :
"All data from eS-WiFi module will be post-padded with 0x15(NAK) to an even number of bytes."
So why are you removing the part about 0x15 padding management ? Can't you keep it as well ?

**Comment by JeanMarcR** [comment]
@LMESTM 
I'd prefer to see 2 separate commits : **ok**
The Inventek firmware sepc clearly mentions 0x15 padding, but nothing about 0x3E, so I'm not sure to understand
**The received ASCII string is the following one:
0x3E 0x15 0x15 0x15 0x15 ...
0x15 is padding character.
In the code, it is easier to check Ox3E and after flush the buffer rather than collect an useless 0x15 and flush the buffer and manage index buffer...
I suggest to explain that in the comment.**

**Comment by JeanMarcR** [comment]
@LMESTM 
So why are you removing the part about 0x15 padding management ?
**Because I think this part is useless. The work is done by the AT parser and thus the error is no longer propagated in the upper layers (ISM43362).**

**Comment by LMESTM** [comment]
> @LMESTM
> So why are you removing the part about 0x15 padding management ?
> **Because I think this part is useless. The work is done by the AT parser and thus the error is no longer propagated in the upper layers (ISM43362).**

I don't think that the AT parser can access inside the DATA PACKETS, I think that's why we have this part of code.
Have you seen better stability or test results after removing this piece of code ? 
Otherwise I would recommend to make 3 commits :
- Add lock/unlock => launch non-reg testing and verify improvements
- Add new padding management in AT parser => launch non-reg testing and verify improvements
- remove 0x15 Padding management => launch non-reg testing and verify improvements
then we can decide.
For now I am not convinced yet that the 3rd step is required, but maybe I will be convinced soon :-)

**Comment by JeanMarcR** [comment]
@LMESTM
"All data from eS-WiFi module will be post-padded with 0x15(NAK) to an even number of bytes."
**Could you give me a pointer to the document ?**

**I made the non-regression test on B-L475E with connectivity-netsocket and 
 connectivity-tls with the three previously described commits.
The result is NO REGRESSION but also NO IMPROVEMENT.**

**I also made some local tests to check that old padding management is useless if new padding management is present ...**

**BUT
indeed there are still some 0x15 present but only in the DATA PACKET.
Neither 0x15 padding management nor new padding management in the AT parser take into account the previous 0x15. For me the treatment of such 0x15 could take place in a second step.**

**Comment by JeanMarcR** [comment]
@LMESTM 
I think that 0x15 present in DATA PACKET are taken into account by code following the comment:
    /*  If there are spurious 0x15 at the end of the data, this is an error
     *  we hall can get rid off of them :-(
     *  This should not happen, but let's try to clean-up anyway
     */
in ISM43362.cpp file. I did not remove the code in my commits.

**Comment by JeanMarcR** [comment]
@LMESTM 
To clarify the situation, I am going to build the 3 commits.

Best regards.

**Comment by LMESTM** [comment]
@JeanMarcR  ok I thought you were removing this part of file: https://github.com/ARMmbed/wifi-ism43362/blob/43b8123e75e30a2547bbebb9b7c3f6822905a401/ISM43362/ISM43362.cpp#L807

 I better understand now - that's okay for me.

**Review by LMESTM — APPROVED** [review]
Goot to go, thanks @JeanMarcR  !

**Comment by LMESTM** [comment]
One slight comment : [WIP] should have been updated before merging :-)

**Pull request merged**
